// Generated by "npm run sync:changelog" from CHANGELOG.md. Do not edit by hand.
const CHANGELOG = [
 {
  "version": "Unreleased",
  "items": [
   {
    "title": "Your loops can go where other people will find them",
    "body": "There is a gallery now. Put a loop in it from the loop editor, browse by newest, most liked, or only people you follow, and add anything you hear straight into your own loops with the author's name still on it. Profiles carry a line about you and a colour. Following each other both ways makes you friends. A shared loop is a recipe, not a recording: notes, an instrument name and a length, a few hundred bytes. That is why this can exist for free, and why nothing in it accepts audio. Reports are per person, three from different people takes a loop down on its own, and it can be put back."
   },
   {
    "title": "The piano roll suggests what comes next",
    "body": "Write a chord or two and it works out where they sit in the key, then offers the one that usually follows. Tab adds it, Shift+Tab picks a different option. It says \"G major\", not \"V\", because nobody should need theory to use it, and it can be turned off in Settings."
   },
   {
    "title": "fabu works on a phone",
    "body": "Not as a compromise: dragging patterns, the piano roll, the loop library and the mixer all work with a finger. Press and hold a loop to pick it up. The track list no longer eats the whole screen, the toolbar keeps every tool instead of quietly dropping them, and windows open as sheets along the bottom."
   },
   {
    "title": "Being removed from a room now sticks",
    "body": "Moderation used to key on the display name, which is typed in by the person being moderated, so a kick lasted as long as it took to pick a new one. It does not any more. If somebody clears their browser and comes back on the same connection, the host is told by name and gets a \"let them in\" button, in case it turns out to be somebody's brother on the same wifi."
   },
   {
    "title": "Humanize, and real automation curves",
    "body": "Nudge timing and loudness slightly so a part sounds played rather than programmed. Automation points can ease in and out instead of only running straight between each other."
   }
  ]
 },
 {
  "version": "1.2.4",
  "items": [
   {
    "title": "Paint effects across patterns",
    "body": "Hold shift and the effect cards turn green with a plus. Drag one across the timeline and it lands on every pattern you pass over, once each, so you can put reverb on a whole section in one stroke. Let go and start again to apply the same effect a second time."
   },
   {
    "title": "A pattern with effects on it now looks like one",
    "body": "A quiet gold edge you can pick out across the whole timeline, and a badge that names what is on it for a few seconds before shrinking back out of the way. The names stay on hover. When an effect lands there is a single sweep across the pattern, and then it leaves you alone."
   },
   {
    "title": "Exports cannot clip any more",
    "body": "Stack enough loops and the mix could push past what a sound file can hold, and the result was crackle on the loudest moments. There is a ceiling on the way out now. Quiet and normal projects are completely untouched by it; it only catches what would have broken."
   },
   {
    "title": "A loop for every instrument, and a jazz section",
    "body": "Every instrument in the list now has at least one loop, so you can hear what each one sounds like without writing anything. The jazz set is built to be stacked: swing ride, brush shuffle, walking bass, piano comping, trumpet and sax written as call and answer, vibes and horn stabs. All of it is in the same key as the rest, so anything layers with anything."
   },
   {
    "title": "Dragging feels like dragging",
    "body": "The card follows your cursor and swings from your hand instead of sitting frozen, patterns lean the way you are moving them, and letting go scatters the card into dust rather than blinking it out."
   },
   {
    "title": "A properly redone export window",
    "body": "It tells you what you are exporting and how big each format will be, with the audio formats separated from MIDI and separate tracks, which are a different kind of thing entirely."
   },
   {
    "title": "MIDI files come out with useful track names",
    "body": "A track called Instrument 2 tells another program nothing, so if you have not named a track, the name of its longest pattern is used, or failing that the instrument."
   },
   {
    "title": "Smaller things",
    "body": ""
   },
   {
    "title": "",
    "body": "Settings opens from the home screen properly instead of behind it, and no longer suggests that per song options apply to everything."
   },
   {
    "title": "",
    "body": "The time signature moved onto the bar counter in the top bar, where it belongs. Click it."
   },
   {
    "title": "",
    "body": "Removed the Downlifter and Sax Stabs presets."
   },
   {
    "title": "",
    "body": "Sub Bass actually uses the 808 now, House Bass sits between the kicks instead of on top of them, and hi-hats have accents rather than being flat."
   }
  ]
 },
 {
  "version": "1.2.3",
  "items": [
   {
    "title": "Everyone in a room needs the same version now",
    "body": "The project format and the way rooms sync both change between releases, and a mismatched player did not fail cleanly, it quietly broke things. So joining now checks the version, and if it does not match you are told exactly what you need and where to get it. If you are ahead of the host it says so and points you at the older build, because that one is not your fault. Update together with whoever you jam with."
   },
   {
    "title": "Trumpet, flute, saxophone and a real organ",
    "body": "Actual recordings, not synths pretending. The organ replaces the old synthesised one, so projects using it just sound better with nothing to change. The trumpet records slightly flat and the saxophone slightly sharp, the way real instruments do, and fabu now corrects for that so they play in tune with everything else. The old \"Keys\" is gone. It was a synthesised piano standing next to a real recorded grand, and there was no reason to keep both. Projects that used it move to the Grand Piano on their own."
   },
   {
    "title": "Export MIDI",
    "body": "The notes, not the sound, so you can take a song into another program. Tempo, time signature, every track and the sustain pedal all come across."
   },
   {
    "title": "Time signature moved to the bar counter",
    "body": "It sits with the bar and beat display in the top bar, where it belongs, and clicking it changes it. It was in Settings before, which made a property of the song look like a setting for the whole app. Settings is now split into what belongs to the song and what belongs to fabu, and it opens from the home screen too."
   },
   {
    "title": "Rooms are safer",
    "body": "The server now refuses messages aimed at a room the sender never joined. Before this, anyone who knew a room code could push things into it without being in it, which meant none of the host's controls applied to them. It also limits how fast and how much anyone can send. This one is already live and protects you whether or not you update."
   },
   {
    "title": "Big songs and long files stopped breaking",
    "body": "Opening the note editor on a long piece could come up blank or full of broken boxes, and zooming into a busy project could leave patterns empty. Both were the same cause and both are fixed."
   },
   {
    "title": "Exports could come out silent",
    "body": "If you opened a project and exported straight away, before the instrument sounds had finished loading, you got a file with nothing in it. Every export now waits for them. A related problem could leave one instrument silent for a whole session after a single hiccup while loading, with nothing on screen to say so."
   },
   {
    "title": "Opening a project from a newer version warns you first",
    "body": "Saving over it would quietly throw away anything the newer version added, so now you get the choice."
   }
  ]
 },
 {
  "version": "1.2.2",
  "items": [
   {
    "title": "Windows: please download this one from the website",
    "body": "Updating from inside the app is broken on Windows and has been for a while. It half installs, gives up, and leaves you with no fabu at all. That is fixed, but the fix lives in this version, so it cannot rescue the update into it. Grab the installer from the site this once and in app updates will work normally from here on. Sorry about that one."
   },
   {
    "title": "Drop a MIDI file onto the timeline",
    "body": "It becomes real patterns you can open and edit, not a locked block of audio. Every part of the file gets its own lane, split wherever the file changes instrument, so a piece that goes piano, then trumpet, then violin arrives as three lanes you can move around separately. Drum parts land on their own lane too. Each lane starts on the closest instrument fabu has, or the grand piano when nothing is close. Drop one into an empty project and the project reshapes itself to fit: tempo, time signature and the file's name. Drop one into a project you are already working on and it asks before touching your tempo."
   },
   {
    "title": "Sustain pedal",
    "body": "Hold Shift while the keyboard is open, click the Sustain button, or use a real pedal on a MIDI keyboard. Notes keep ringing after you let go, like a real piano. It records as you play it, it comes through in exported files, and you can draw it by hand in the piano roll on the strip under the bar numbers. MIDI files bring their pedal with them, which is most of what makes a piano piece sound like one."
   },
   {
    "title": "Time signatures",
    "body": "3/4, 6/8 and the rest, in Settings. The ruler, the bar numbers, the metronome accent and where patterns snap all follow it."
   },
   {
    "title": "New projects start empty",
    "body": "No lanes to clear out first. Add what you want with the Instrument and Audio buttons. The walkthrough for new users starts there now."
   },
   {
    "title": "Windows remember their size and place",
    "body": "The main window and every panel inside it. Size the mixer how you like it once and it stays that way."
   },
   {
    "title": "Big songs stopped breaking",
    "body": "Opening the piano roll on a long piece could come up blank or full of broken boxes, and zooming into a busy project could leave clips empty. Both were the same thing: the app was asking for a drawing surface far larger than the browser allows, and being handed nothing. It now draws only the part you can see. A four thousand note part redraws in about a millisecond."
   },
   {
    "title": "Jam rooms hold together",
    "body": "The server sleeps when nobody is using it and can take a few seconds to wake. The app used to give up before that and the room would just die. Now it keeps trying quietly and puts you back without anyone seeing you leave. Lose your wifi and get it back and you land in the same room."
   },
   {
    "title": "When something goes wrong it says so",
    "body": "Every way a room can break now has a real sentence attached. \"Servers went down.\" \"You are offline.\" \"Host disconnected.\" No more guessing whether it is you, your internet or the app. If it can be retried there is a button, and your work is saved before anything else happens."
   },
   {
    "title": "Rooms use a fraction of the traffic",
    "body": "Project changes are compressed, cursors slow down as a room fills and switch off past forty people, and the presence heartbeat eases off too. A hundred people in one room went from impossible to tested and working."
   },
   {
    "title": "The host leaving is no longer a game show",
    "body": "The spinning name picker is gone. If the host drops it waits a moment in case they are reconnecting, then hands over quietly and tells you who has it."
   },
   {
    "title": "Smaller things",
    "body": ""
   }
  ]
 },
 {
  "version": "1.2.1",
  "items": [
   {
    "title": "",
    "body": "\"Restart in 1 minute\" no longer traps you. It now counts down in a small bar in the corner so you can keep working and save, restart early, or cancel it."
   },
   {
    "title": "",
    "body": "Section markers work again. Naming one opened a dialog the desktop app cannot show, so right-clicking the ruler often did nothing at all."
   },
   {
    "title": "",
    "body": "Right-clicking the ruler no longer grabs and drags the repeat region. It opens a proper menu: add or remove a marker, turn repeat on or off, and clear it."
   },
   {
    "title": "",
    "body": "You can clear the repeat region now."
   },
   {
    "title": "",
    "body": "The piano roll opens where the instrument actually lives, so a bass starts in the low octaves instead of the high ones where it sounds wrong."
   },
   {
    "title": "",
    "body": "808 Bass keeps its character higher up the keyboard instead of turning into a whistle."
   },
   {
    "title": "",
    "body": "The shortcut list is up to date again, including repeat, grouping, scrubbing, automation and dragging a clip out to a new track."
   }
  ]
 },
 {
  "version": "1.2.0",
  "items": [
   {
    "title": "",
    "body": "Multiplayer security: the host now checks every change that comes in and undoes anything that breaks the room rules. Before this, the rules only ran on the other person's computer, so a modified app could ignore them. Someone who is removed is now really removed, even if their app pretends otherwise."
   },
   {
    "title": "",
    "body": "Accounts: the signed-in name updates properly. It no longer keeps showing the old username after logging out, logging in as someone else, or having the name changed."
   },
   {
    "title": "",
    "body": "Clearer sign-in messages: \"Username already taken\", \"Wrong password\", and \"No account called X. Want to create one?\" with a button that takes you straight to registering."
   },
   {
    "title": "",
    "body": "Usernames are checked against a profanity list."
   }
  ]
 }
];
