// Generated by "npm run sync:version" from package.json. Do not edit by hand.
// The desktop app overrides this with the real packaged version at startup;
// the web build has no such source, so this constant is what it goes by.
const APP_VERSION = "1.2.4";
